apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2      # enable horizontal scaling
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: auth
        # image: 123banzhang/oasis-auth:1.1
        image: 123banzhang/oasis-auth:2.3
        resources:
          limits:
            memory: "384Mi"       # enable vertical scaling
            cpu: "375m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
      - name: service
        image: 123banzhang/oasis-service:2.0
        resources:
          limits:
            memory: "640Mi"
            cpu: "750m"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 60
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-lb
spec:
  selector:
    app: springboot-app
  ports:
    - name: auth
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: service-service-lb
spec:
  selector:
    app: springboot-app
  ports:
    - name: service
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
