spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oasis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 1800000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1
#      hikari:
#        pool-name: DateHikariCP
#        minimum-idle: 5
#        #?????????????10??
#        idle-timeout: 1800000
#        #????????10
#        maximum-pool-size: 10
#        #?????????????
#        auto-commit: true
#        #?????????0?????????1800000?30???
#        max-lifetime: 1800000
#        #?????????30000?30??
#        connection-timeout: 3000
#        #?????????????
#        connection-test-query: SELECT 1
#      #监控配置
#      stat-view-servlet:
#        enabled: true
#        login-username: root
#        login-password: 123456
#        url-pattern: /druid/*

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
  level:
    com:
      sys: debug

#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 10MB
#
#  #thymeleaf的配置
#  thymeleaf:
#    cache: false
#    enabled: true
#
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
##配置mybatisplus
#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    db-config:
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##shiro的配置
#shiro:
#  hash-algorithm-name: md5
#  hash-iterations: 2
#  anon-urls:
#    - /index.html*
#    - /sys/toLogin*
#    - /login/login*
#    - /login/getCode
#    - /resources/**
#  login-url: /index.html
#  log-out-url: /login/logout*
#  authc-ulrs:
#    - /**

##修改端口号为8080
#server:
#  port: 8080
